### ISSUE TITLE
when I import matminer，mistake as following:ValueError: Unexpected atomic number Z=119。

### ISSUE THREAD

**Issue by chaserlight19942007** [hackingmaterials/matminer#924] opened 2024-02-08 07:13 UTC
Dear developer:
I'm having some problems with my python task, here's the exact description:
version of pymatgen:2024.1.27
version of matminer:0.9.0
version of python:3.12
my codes:
from matminer.datasets import load_dataset
from matminer.featurizers.composition import ElementProperty
from matminer.featurizers.conversions import StrToComposition

bandgaps = load_dataset('matbench_expt_gap')
bandgaps = bandgaps[bandgaps['gap expt'] > 0].reset_index(drop=True)
bandgaps.head()

str_to_comp = StrToComposition(target_col_id='composition_pmg')
bandgaps_comp = str_to_comp.featurize_dataframe(bandgaps, col_id='composition')

featurizer = ElementProperty.from_preset('magpie')
bandgaps_data_featurized = featurizer.featurize_dataframe(bandgaps_comp, col_id='composition_pmg', ignore_errors=True,
                                                          return_errors=True)
y = bandgaps_data_featurized['gap expt']
bandgaps_data_featurized.head()

mistakes are showing:
File D:\python\python-machine-learning\venv\Lib\site-packages\matminer\featurizers\composition\element.py:202
    198     def implementors(self):
    199         return ["Jiming Chen", "Logan Ward"]
--> 202 class BandCenter(BaseFeaturizer):
    203     """
    204     Estimation of absolute position of band center using electronegativity.
    205 
    206     Features
    207         - Band center
    208     """
    210     magpie_data = MagpieData()

File D:\python\python-machine-learning\venv\Lib\site-packages\matminer\featurizers\composition\element.py:210, in BandCenter()
    202 class BandCenter(BaseFeaturizer):
    203     """
    204     Estimation of absolute position of band center using electronegativity.
    205 
    206     Features
    207         - Band center
    208     """
--> 210     magpie_data = MagpieData()
    211     deml_data = DemlData()
    213     def featurize(self, comp):

File D:\python\python-machine-learning\venv\Lib\site-packages\matminer\utils\data.py:217, in MagpieData.__init__(self)
    215 except (ValueError, IndexError):
    216     prop_value = float("NaN")
--> 217 self.all_elemental_props[descriptor_name][Element.from_Z(atomic_no).symbol] = prop_value

File D:\python\python-machine-learning\venv\Lib\site-packages\pymatgen\core\periodic_table.py:526, in ElementBase.from_Z(Z, A)
    524     if data["Atomic no"] == Z and atomic_mass_num == A:
    525         return Element(sym)
--> 526 raise ValueError(f"Unexpected atomic number {Z=}")

ValueError: Unexpected atomic number Z=119
So how can I solve this problem? Thanks!

**Comment by ml-evs** [comment] 2024-02-08 09:51
This is a duplicate of #919 and #920, which is fixed in #921, please search for messages before raising an issue! You can find two options to deal with it listed in those issues, either downgrade pymatgen to a supported version or install matminer directly in this repo.

**Closed** 2024-02-08 09:51 UTC

**Comment by chaserlight19942007** [comment] 2024-02-08 14:07
thanks， I downgrade the version of pymatgen as 2023.12.18 and solve this problem

**Comment by ml-evs** [comment] 2024-02-08 14:17
Great, glad to hear it! I also just noticed you are brand new on GitHub (welcome!) -- hopefully my answer was clear regarding links to the other issues.
