### ISSUE TITLE
Move figrecipes to a different repo, or delete it

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#453] opened 2020-05-01 22:01 UTC
Most of what Figrecipes does in matminer (currently) is cause failing tests from plotly updates. It's not well maintained, and for good reason - no one (to my knowledge) actually uses it.

The pros/cons as far as I see them break down as:

#### Pros:
- less code bloat
- fewer random test/CI failures due to plotly updates/incompatibilities
- faster pip install and fewer pip issues

#### Cons:
- notebooks in matminer_examples which rely on it would stop working (workaround: move figrecipes to its own repo and update the notebooks accordingly)

Anyone have thoughts on this @computron @WardLT @utf ?

**Comment by WardLT** [comment] 2020-05-01 22:34
I'm in favor of dropping it, especially if it is not very well used.

**Comment by computron** [comment] 2020-05-02 21:01
Just to point out that this was suggested awhile ago (e.g. in favor of trying to work with something like https://github.com/santosjorge/cufflinks), with @ardunn being the one of the ones insisting on keeping FigRecipes around :P

Anyway, since Figrecipes is part of the published matminer paper, I suggest just moving it to a separate repo and putting a note in matminer that it's now somewhere else. That way, it still exists - e.g., people wanting to reproduce old code examples, etc.

I would support redoing the notebooks using some other tool than Figrecipes, just not sure if someone will actually do it. If not then you can just import Figrecipes from whatever new repo it's in.

**Comment by ardunn** [comment] 2020-05-04 02:49
Hah! Probably so. But the times change and so should we.

Ok so sounds like the consensus is to move it to another repo.

**Comment by computron** [comment] 2020-05-04 16:15
Yes you can consider moving to another repo as "approved"

**Closed** 2021-06-07 23:25 UTC
